//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Locales.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abu Dhabi Police General Headquarters is committed to provide customers with the best service possible and to receive and tackle complaints to ensure that these complaints are not going to be repeated. Besides, it will organize all types and degrees of seriousness of the complaint process for customers and allows all customers, suppliers and partners to express their opinions, comments and feedback, file complaints about a service or an incident..
        /// </summary>
        public static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong. Please Try After Sometime.
        /// </summary>
        public static string applicationError {
            get {
                return ResourceManager.GetString("applicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has been submitted successfuly, your application ID:.
        /// </summary>
        public static string applicationSuccessSubmit {
            get {
                return ResourceManager.GetString("applicationSuccessSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abu Dhabi Police CAS System .
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Complaint.
        /// </summary>
        public static string btnComplaint {
            get {
                return ResourceManager.GetString("btnComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up.
        /// </summary>
        public static string btnFollowUp {
            get {
                return ResourceManager.GetString("btnFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Time for Communication.
        /// </summary>
        public static string CallTimes {
            get {
                return ResourceManager.GetString("CallTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value you entered is not correct..
        /// </summary>
        public static string CaptchaErrorMessage {
            get {
                return ResourceManager.GetString("CaptchaErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code.
        /// </summary>
        public static string CaptchaMessage {
            get {
                return ResourceManager.GetString("CaptchaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Id.
        /// </summary>
        public static string ChannedId {
            get {
                return ResourceManager.GetString("ChannedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Number.
        /// </summary>
        public static string companyNo {
            get {
                return ResourceManager.GetString("companyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Number is Required.
        /// </summary>
        public static string companyNoRequired {
            get {
                return ResourceManager.GetString("companyNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints.
        /// </summary>
        public static string complainApplicationName {
            get {
                return ResourceManager.GetString("complainApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complainer Type.
        /// </summary>
        public static string ComplainerType {
            get {
                return ResourceManager.GetString("ComplainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complainer Type Error.
        /// </summary>
        public static string ComplainerTypeError {
            get {
                return ResourceManager.GetString("ComplainerTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Against Driver.
        /// </summary>
        public static string ComplaintAgainstDriver {
            get {
                return ResourceManager.GetString("ComplaintAgainstDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Against Traffic Fines.
        /// </summary>
        public static string ComplaintAgainstTrafficFines {
            get {
                return ResourceManager.GetString("ComplaintAgainstTrafficFines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Against Traffic Fine.
        /// </summary>
        public static string ComplaintAgainstVehicle {
            get {
                return ResourceManager.GetString("ComplaintAgainstVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objection to a traffic violation.
        /// </summary>
        public static string ComplaintAgianstViolation {
            get {
                return ResourceManager.GetString("ComplaintAgianstViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint ID.
        /// </summary>
        public static string complaintid {
            get {
                return ResourceManager.GetString("complaintid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Kind.
        /// </summary>
        public static string ComplaintKind {
            get {
                return ResourceManager.GetString("ComplaintKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint kind must be selected.
        /// </summary>
        public static string ComplaintKindRequired {
            get {
                return ResourceManager.GetString("ComplaintKindRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Complaints.
        /// </summary>
        public static string ComplaintTraffic {
            get {
                return ResourceManager.GetString("ComplaintTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Type.
        /// </summary>
        public static string complainttype {
            get {
                return ResourceManager.GetString("complainttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Complaint.
        /// </summary>
        public static string CurrentPage {
            get {
                return ResourceManager.GetString("CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Solution.
        /// </summary>
        public static string customerSolution {
            get {
                return ResourceManager.GetString("customerSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Streaming Video with Abu Dhabi Police GHQ.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Enter Suggestion Detail.
        /// </summary>
        public static string detailRequired {
            get {
                return ResourceManager.GetString("detailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint details must be entered.
        /// </summary>
        public static string DetailsRequired {
            get {
                return ResourceManager.GetString("DetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates ID.
        /// </summary>
        public static string EID {
            get {
                return ResourceManager.GetString("EID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates ID must be entered.
        /// </summary>
        public static string EIDRequired {
            get {
                return ResourceManager.GetString("EIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid.
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be entered.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirate.
        /// </summary>
        public static string EmiID {
            get {
                return ResourceManager.GetString("EmiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates ID.
        /// </summary>
        public static string EmiratesID {
            get {
                return ResourceManager.GetString("EmiratesID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates Identity must be 15 digits.
        /// </summary>
        public static string EmiratesIdentityError {
            get {
                return ResourceManager.GetString("EmiratesIdentityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while submitting your complaint.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jpeg, .png, .gif.
        /// </summary>
        public static string fileExtensions {
            get {
                return ResourceManager.GetString("fileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 MB.
        /// </summary>
        public static string fileSize {
            get {
                return ResourceManager.GetString("fileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum upload file size: .
        /// </summary>
        public static string filesizeinfo {
            get {
                return ResourceManager.GetString("filesizeinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type:.
        /// </summary>
        public static string filetype {
            get {
                return ResourceManager.GetString("filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Number.
        /// </summary>
        public static string fineNumber {
            get {
                return ResourceManager.GetString("fineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Type.
        /// </summary>
        public static string fineType {
            get {
                return ResourceManager.GetString("fineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FollowUp Complaint&apos;s Status.
        /// </summary>
        public static string FollowUp {
            get {
                return ResourceManager.GetString("FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the form below.
        /// </summary>
        public static string formTitle {
            get {
                return ResourceManager.GetString("formTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is Required.
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GenderType {
            get {
                return ResourceManager.GetString("GenderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string generalError {
            get {
                return ResourceManager.GetString("generalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Image Type (Only jpg,jpeg,png are allowed).
        /// </summary>
        public static string ImageInvalid {
            get {
                return ResourceManager.GetString("ImageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string KindDetail {
            get {
                return ResourceManager.GetString("KindDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select Suggestion Kind.
        /// </summary>
        public static string kindRequired {
            get {
                return ResourceManager.GetString("kindRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know Your Rights.
        /// </summary>
        public static string KnowYourRights {
            get {
                return ResourceManager.GetString("KnowYourRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        public static string langArabic {
            get {
                return ResourceManager.GetString("langArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details should have minumum of 25 Characters.
        /// </summary>
        public static string lengthError {
            get {
                return ResourceManager.GetString("lengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints And Suggestions.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAS.
        /// </summary>
        public static string MainSmall {
            get {
                return ResourceManager.GetString("MainSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Type.
        /// </summary>
        public static string MainType {
            get {
                return ResourceManager.GetString("MainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion Details.
        /// </summary>
        public static string menuApplicationDesc {
            get {
                return ResourceManager.GetString("menuApplicationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        public static string menuApplicationName {
            get {
                return ResourceManager.GetString("menuApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string menuSearch {
            get {
                return ResourceManager.GetString("menuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Number.
        /// </summary>
        public static string Mid {
            get {
                return ResourceManager.GetString("Mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number is not valie (ex:0501234567).
        /// </summary>
        public static string mobileError {
            get {
                return ResourceManager.GetString("mobileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile format is invalid.
        /// </summary>
        public static string MobileFormat {
            get {
                return ResourceManager.GetString("MobileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number must be entered.
        /// </summary>
        public static string mobileRequired {
            get {
                return ResourceManager.GetString("mobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Suggestion.
        /// </summary>
        public static string modelName {
            get {
                return ResourceManager.GetString("modelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in English.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be entered.
        /// </summary>
        public static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been sent to your mobile.
        /// </summary>
        public static string otpsent {
            get {
                return ResourceManager.GetString("otpsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Category.
        /// </summary>
        public static string PlateCategory {
            get {
                return ResourceManager.GetString("PlateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Color.
        /// </summary>
        public static string plateColor {
            get {
                return ResourceManager.GetString("plateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Color.
        /// </summary>
        public static string PlateColors {
            get {
                return ResourceManager.GetString("PlateColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number.
        /// </summary>
        public static string plateNo {
            get {
                return ResourceManager.GetString("plateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number.
        /// </summary>
        public static string plateNumber {
            get {
                return ResourceManager.GetString("plateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number Should Contains Only Numbers.
        /// </summary>
        public static string plateNumberError {
            get {
                return ResourceManager.GetString("plateNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Source.
        /// </summary>
        public static string PlateSource {
            get {
                return ResourceManager.GetString("PlateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string pleaseselect {
            get {
                return ResourceManager.GetString("pleaseselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter value for the Emirates Identity.
        /// </summary>
        public static string RequiredEmiratesIdentity {
            get {
                return ResourceManager.GetString("RequiredEmiratesIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are required fields.
        /// </summary>
        public static string requiredFields {
            get {
                return ResourceManager.GetString("requiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Kind.
        /// </summary>
        public static string ResourcesKind {
            get {
                return ResourceManager.GetString("ResourcesKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Kind Required.
        /// </summary>
        public static string ResourcesKindRequired {
            get {
                return ResourceManager.GetString("ResourcesKindRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please search your registered complaints.
        /// </summary>
        public static string searchsubtitle {
            get {
                return ResourceManager.GetString("searchsubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select type of complaint you want to register..
        /// </summary>
        public static string selectComplainttype {
            get {
                return ResourceManager.GetString("selectComplainttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Solution.
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Streams List.
        /// </summary>
        public static string StreamsList {
            get {
                return ResourceManager.GetString("StreamsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Type.
        /// </summary>
        public static string SubType {
            get {
                return ResourceManager.GetString("SubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to the Terms and Conditions.
        /// </summary>
        public static string tandc {
            get {
                return ResourceManager.GetString("tandc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to the Terms and Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Streaming.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified ID Number.
        /// </summary>
        public static string UID {
            get {
                return ResourceManager.GetString("UID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified ID must be entered.
        /// </summary>
        public static string UIDRequired {
            get {
                return ResourceManager.GetString("UIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified ID.
        /// </summary>
        public static string UnifiedID {
            get {
                return ResourceManager.GetString("UnifiedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unified number contains numbers only.
        /// </summary>
        public static string UnifiedIDError {
            get {
                return ResourceManager.GetString("UnifiedIDError", resourceCulture);
            }
        }
    }
}
